Iter8
spaceosint/short-url pull request #11
Opened 2023-02-13 21:43 UTC by spaceosint

2023-02-15 20:21 UTC, molchalin commented on internal/storage/inmemory.go
> +func (s *InMemory) GetAll(cfg config.Config) ([]filestore.Event, error) {
Давай все таки сделаем две реализации. Одна в памяти, другая в памяти + на диске

2023-02-15 20:21 UTC, molchalin commented on internal/storage/filestore/filestore.go
> +	file, err := os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0777)
файл надо закрывать, когда перестаешь им пользоваться. Иначе через какое то время количество открытых файлов превысит лимит, и приложение упадёт с ошибкой

2023-02-15 20:21 UTC, molchalin commented on internal/middleware/middelware.go
> +		if !strings.Contains(c.Request.Header.Get("Content-Type"), "gzip") {
По идее должно быть в заголовке Content-Encoding

2023-02-15 20:21 UTC, molchalin commented on internal/middleware/middelware.go
> +func GzipHandle() gin.HandlerFunc {
А для шифрования тела?

2023-02-15 20:21 UTC, molchalin commented on cmd/shortener/main.go
> +	serverAddress := flag.String("a", getEnv("SERVER_ADDRESS", "127.0.0.1:8080"), "a string")
Приоритет флага тут получается выше, а надо наоборот

2023-02-15 20:21 UTC, molchalin commented on internal/app/handlers/handlers.go
> +func (h *Handler) PostNewUserURL(c *gin.Context) {
а зачем нам энкодить один только identifier, почему не структуру целиком?

2023-02-26 19:53 UTC, molchalin commented on internal/app/pkg/app/app.go
> +	a.r.Use(gzip.Gzip(gzip.DefaultCompression))
Эту мидлвару нужно написать самостоятельно

2023-02-26 19:53 UTC, molchalin commented on internal/app/handlers/handlers.go
> +		resp, err := h.fileStorage.AddNewLinkFile(h.cfg, newUserURL.OriginalURL)
В хендлерах не должно содержаться логики хранения. У тебя есть интерфейс стораджа. В main при инициализации стораджа в зависимости от конфигурации нужно выбрать либо файл сторадж, либо инмемори. И хендлер будет просто звать методы стораджа, без понимания, какая логика хранения используется. Если есть какие то вопросы, то можно обсудить это на 1-1

2023-02-26 19:53 UTC, molchalin commented on cmd/shortener/main.go
> +	if cfg.FileStoragePath == "" {
Как то все выглядит сложно. Может просто распарсить флаги, и использовать значения флагов как дефолтные для енвов ?

2023-04-12 16:03 UTC, tmvrus requested changes
тесты не прошли
https://github.com/spaceosint/short-url/actions/runs/4621034764/jobs/8171956699?pr=11#step:6:30

2023-04-13 22:30 UTC, tmvrus requested changes
- большое количество бесполезных комментариев
- функций в приложении стало больше а тестов меньше
- где-то для логирования используется fmt.Println  а где-то log.Print, хорошо бы придерживаться единообразия
- перед следующим ревью лучше создать новый PR

2023-04-13 22:30 UTC, tmvrus commented on cmd/shortener/main.go
> +	fileStoragePath := flag.String("f", getEnv("FILE_STORAGE_PATH", ""), "a string")
`flag.String` вторым аргументом принимает дефолтное значение, он успешно будет заменено на значение из командной строки, хотя задание прямо говорит об обратном
<img width="640" alt="image" src="https://user-images.githubusercontent.com/554425/231891071-f252a056-71d8-4464-8b1a-39e4614c061e.png">

2023-04-13 22:30 UTC, tmvrus commented on cmd/shortener/main.go
> +// main
бессмысленней комментарий

2023-04-13 22:30 UTC, tmvrus commented on cmd/shortener/main.go
> +	//awqd
бессмысленней комментарий

2023-04-13 22:30 UTC, tmvrus commented on internal/app/handlers/handlers_test.go
> +//				inputBody            string
в рабочем проекте не должно быть закомментированного кода, это засоряет проект и усложняет чтение

2023-04-13 22:30 UTC, tmvrus commented on internal/app/handlers/handlers.go
> +	}
в данном случае, хорошо бы клиенту вместо `MyError{"bed_request_json"}` ответить что именно не так с json, тем более что в `err` эта информация есть

2023-04-13 22:30 UTC, tmvrus commented on internal/app/handlers/handlers.go
> +	}
log.Fatal инициирует завершение работы всего приложения, но в данном случае это просто ошибка уровня storage, она не должна ронять приложение целиком

2023-04-13 22:30 UTC, tmvrus commented on internal/app/handlers/handlers.go
> +	}
log.Fatal инициирует завершение работы всего приложения, но в данном случае это просто ошибка уровня storage, она не должна ронять приложение целиком

2023-04-13 22:30 UTC, tmvrus commented on internal/app/handlers/handlers.go
> +
если ошибка не storage.ErrNotFound  и не errors.Is(err, storage.ErrAlreadyExists), мы ответим клиенту что все хорошо, разве так правильно?

2023-04-13 22:30 UTC, tmvrus commented on internal/app/pkg/app/app.go
>  	a.r.GET("/fwfwrfwfwhfwedscwewfgtgbrgf3r34fwc43c34fcwcxe2d2f43g544g5g34f24f23f4f", a.h.GetUsersURL)
выглядит очень странно

2023-04-13 22:30 UTC, tmvrus commented on internal/config/config.go
> +//var once sync.Once
бесполезные комментарии

2023-04-13 22:30 UTC, tmvrus commented on internal/config/config.go
> +}
бесполезные комментарии

2023-04-13 22:30 UTC, tmvrus commented on cmd/shortener/main.go
> +		cfg.ServerAddress = *serverAddress
если я через evn захочу установить значение "127.0.0.1:8080" то оно перезапишется на значение из serverAddress, дальше похожая ситуация, рекомендую модуль блок конфигурирования

2023-04-13 22:30 UTC, tmvrus commented on internal/storage/inmemory/inmemory.go
> +}
это очень странный код:
- ошибки просто выводятся и не влияют на работу
- в конце всегда возвращается одна и та же ошибка
- зачем map[string]string превращается в json затем идет попытка превратить это в структуру, которая не вполне соответствует данным, и все это для того что бы просто напечатать структуру, хотя можно было сразу напечатать содержимое `s.m` 

это надо либо убрать, либо постараться найти объяснение

2023-04-13 22:30 UTC, tmvrus commented on internal/storage/inmemory/inmemory.go
> +	s.m["OriginalURL"] = newUserURL
а для какой цели записываются ключи "Identifier" и "OriginalURL"?

2023-04-13 22:30 UTC, tmvrus commented on internal/storage/filestore/filestore.go
> +	cons, err := NewConsumer(filePath)
файл после открытия не закрывается, это создает "висячий" файловый дескриптор, операционная система за такое может убить приложение

2023-04-13 22:30 UTC, tmvrus commented on internal/storage/filestore/filestore.go
> +	defer prod.file.Close()
ошибку закрытия файла нужно хотя бы логирвать, иначе может быт ситуация когда логов нет и файл не сохранился

2023-04-18 09:39 UTC, tmvrus requested changes
<img width="674" alt="image" src="https://user-images.githubusercontent.com/554425/232737493-5dbe492a-1c20-42ca-9fc4-6aed8fc088bf.png">
пожалуйста, отнесись к комментариям внимательней

2023-04-18 10:55 UTC, closed without merging